# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PICOCALC_MFD)     += picocalc_mfd/
obj-$(CONFIG_PICOCALC_MFD_KBD) += picocalc_mfd_kbd/
obj-$(CONFIG_PICOCALC_KBD)     += picocalc_kbd/
obj-$(CONFIG_PICOCALC_LCD)     += picocalc_lcd/
obj-$(CONFIG_PICOCALC_SND_PWM)     += picocalc_snd-pwm/
obj-$(CONFIG_PICOCALC_SND_SOFT_PWM)     += picocalc_snd-softpwm/
